### PR TITLE
Update precached.conf

### PR DESCRIPTION
**Pull request by idnovic**
added a few binaries as I saw fit

### CODE REVIEW

**Comment by idnovic** [comment]
you may have seen the /usr/bin/qemu-system-x86_64
I do not want to add every single qemu image by hand, is something like
/usr/bin/qemu* possible with precached?

I do not thing it is useful to preload any qemu image, these are just the base emulation images.

**Comment by X3n0m0rph59** [comment]
> you may have seen the /usr/bin/qemu-system-x86_64
I do not want to add every single qemu image by hand, is something like
/usr/bin/qemu* possible with precached?

```
program_blacklist = [
   "/usr/bin/qemu-*",
]
```

> I do not thing it is useful to preload any qemu image, these are just the base emulation images.

Yes, you may want to use the file blacklisting feature with globs.

```
blacklist = [
    "/var/lib/libvirt/images/**/*",
]
```

Since this would not be very useful indeed, precached currently employs a hardcoded size limit:

```rust
pub const MAX_ALLOWED_PREFETCH_SIZE: usize = 256 * 1024 * 1024; // 256 MiB
```
Files larger than this will not be prefetched in any case.

**Comment by idnovic** [comment]
what is the difference between `/**/*` and `/*`?

**Comment by X3n0m0rph59** [comment]
The string `/**/` denotes a recursive directory glob, where `/*` means match all files in the directory.
Thus `/var/lib/libvirt/images/**/*` matches all files in all subdirectories of `/var/lib/libvirt/images`.

**Pull request merged**
